# cspell:ignore esbuild, unrs, jotai
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@types/node": ^24.0.10
  babel-plugin-react-compiler: 19.1.0-rc.2
  commonality: ^0.2.63
  commonality-checks-recommended: ^0.0.40
  typescript: ^5.8.3
  vite: ^7.0.2
  vite-plugin-inspect: ^11.3.0
  "@vitejs/plugin-react": ^4.6.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6

catalogs:
  stable:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@vitejs/plugin-rsc": ^0.4.11
  canary:
    react: 19.2.0-canary-5d87cd22-20250704
    react-dom: 19.2.0-canary-5d87cd22-20250704
    "@vitejs/plugin-rsc": https://pkg.pr.new/vitejs/vite-plugin-react/@vitejs/plugin-rsc-canary@ac6028d
  experimental:
    react: 0.0.0-experimental-5d87cd22-20250704
    react-dom: 0.0.0-experimental-5d87cd22-20250704
    "@vitejs/plugin-rsc": https://pkg.pr.new/vitejs/vite-plugin-react/@vitejs/plugin-rsc-experimental@ac6028d

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  "@commonalityco/studio>@xyflow/react": "-"
  "@commonalityco/studio>@xyflow/system": "-"
  "@commonalityco/studio>framer-motion": "-"
  "@commonalityco/studio>jotai": "-"
  "@commonalityco/studio>lz-string": "-"
  "@commonalityco/studio>nuqs": "-"
  "@commonalityco/studio>socket.io-client": "-"
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
